# WATCOM C/C++ Window Classes + Console Output Library Makefile
# Copyright (c) 2000 - 2002 Simon Peter <dn.tlp@gmx.net>

# Disable 'non-portable pointer conversion' warning.
CFLAGS = -wcd=101

OUTPUT = window.lib
OBJS = txtgfx.obj window.obj wndman.obj debug.obj
DIST = txtgfx.c txtgfx.h window.cpp window.h wndman.cpp wndman.h readme.txt &
        debug.c debug.h

include_INST = txtgfx.h window.h wndman.h
lib_INST = window.lib

distfile = window10.zip
includesubdir = window
