# WATCOM C/C++ Timer Library 1.0 Makefile
# Copyright (c) 2001, 2002 Simon Peter <dn.tlp@gmx.net>

OUTPUT = timer.lib
OBJS = timer.obj irq.obj pindos.obj dpmi.obj
DIST = timer.cpp irq.cpp pindos.cpp dpmi.cpp timer.h irq.h pindos.h dpmi.h &
imsrtns.h readme.txt

include_INST = timer.h
lib_INST = timer.lib

distfile = timer11.zip
